FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir uv \
    && uv pip install . --system --no-cache



EXPOSE 3000

CMD ["uvicorn", "apps.interface.server:app", "--host", "0.0.0.0", "--port", "3000"]
